Bootstrap: docker
From: python@sha256:1c26c25390307b64e8ff73e7edf34b4fbeac59d41da41c08da28dc316a721899
Stage: spython-base

%files
dummy_step.py .
%post
# https://hub.docker.com/layers/library/python/3.10/images/sha256-1c26c25390307b64e8ff73e7edf34b4fbeac59d41da41c08da28dc316a721899?context=explore
mkdir -p /input_data
mkdir -p /results
# VOLUME /results
# VOLUME /input_data
pip install pandas==2.1.2 pyarrow

%runscript
exec /usr/local/bin/python dummy_step.py "$@"
%startscript
exec /usr/local/bin/python dummy_step.py "$@"