from linker.pipeline import Pipeline
from linker.configuration import Config
from pathlib import Path


workdir: "src/linker"


config = snakemake.workflow.config


rule all:
    input:
        config["output_file"],


