computing_environment: slurm
container_engine: singularity  # or docker
slurm:
  account: proj_simscience
  partition: all.q
# TODO: Move implementation resources (pipeline.yaml? input spec?)
implementation_resources:
  memory: 10  # GB
  cpus: 2
  time_limit: 1  # hours
