steps:
  step_1:
    implementation:
      name: step_1_python_pandas
      configuration:
        DUMMY_CONTAINER_INCREMENT: 11
  step_2:
    implementation:
      name: step_2_python_pandas
      configuration:
        DUMMY_CONTAINER_INCREMENT: 50
  step_3:
    implementation:
      name: step_3_python_pandas
  choice_section:
    type: simple
    step_4:
      implementation:
        name: step_4_python_pandas
